### ISSUE TITLE
Define moves in terms of LEFT, RIGHT, and STRAIGHT

### ISSUE THREAD

**Issue by motiwari** [motiwari/Snake#27]
From Mike:

"hey one thing that i think might be hurting our snake game is that, because we constrict it within the game to never go backwards, it's never able to adjust the q-values of going backwards and hence it's a source of error. is there some way to allow the player to choose a backwards move in such a way that when the game processes it, it just ignores the move, but still allow the user to select it?

the other thing we could consider is re-orienting and defining the moves in terms of LEFT, RIGHT, and STRAIGHT. that we don't need experience based on backwards moves."

**Comment by MikeSchoenhals** [comment]
hey i've been thinking a little more about the LEFT, RIGHT, STRAIGHT vs LEFT, RIGHT, UP, DOWN thing. I actually think it would be better to stick with LEFT, RIGHT, UP, DOWN, and allow the game to choose backwards moves (which does nothing). Otherwise, the game has to learn orientation, which I think would make things more complicated.

**Comment by motiwari** [comment]
This was closed by b004c3ec4161d1f381144078b03c9b7038ea5141
